language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install -d --system
# command to run tests
script: pytest # Need to review
